import type { DashboardAccount, DashboardTransaction } from "@/lib/finance";

export const sampleAccounts: DashboardAccount[] = [
  {
    id: "acc_checking",
    name: "Orbit Checking",
    subtype: "checking",
    mask: "2034",
    balanceCurrent: 8240,
    balanceAvailable: 8010,
  },
  {
    id: "acc_savings",
    name: "Velocity Savings",
    subtype: "savings",
    mask: "5519",
    balanceCurrent: 19420,
    balanceAvailable: 19420,
  },
  {
    id: "acc_credit",
    name: "Photon Rewards Card",
    subtype: "credit card",
    mask: "9940",
    balanceCurrent: -1120,
    balanceAvailable: 5880,
  },
];

export const sampleTransactions: DashboardTransaction[] = [
  {
    id: "txn_payroll_mar",
    name: "Helios Labs Payroll",
    merchantName: "Helios Labs",
    amount: -6400,
    date: "2026-03-15",
    primaryCategory: "INCOME",
    detailedCategory: "INCOME_WAGES",
    confidence: "VERY_HIGH",
    pending: false,
  },
  {
    id: "txn_rent_mar",
    name: "Hawthorne Lofts",
    merchantName: "Hawthorne Lofts",
    amount: 2150,
    date: "2026-03-02",
    primaryCategory: "RENT_AND_UTILITIES",
    detailedCategory: "RENT_AND_UTILITIES_RENT",
    confidence: "VERY_HIGH",
    pending: false,
  },
  {
    id: "txn_grocery",
    name: "Whole Foods Market",
    merchantName: "Whole Foods",
    amount: 186,
    date: "2026-03-21",
    primaryCategory: "FOOD_AND_DRINK",
    detailedCategory: "FOOD_AND_DRINK_GROCERIES",
    confidence: "HIGH",
    pending: false,
  },
  {
    id: "txn_cafe",
    name: "Blue Bottle Coffee",
    merchantName: "Blue Bottle",
    amount: 22,
    date: "2026-03-22",
    primaryCategory: "FOOD_AND_DRINK",
    detailedCategory: "FOOD_AND_DRINK_COFFEE",
    confidence: "HIGH",
    pending: false,
  },
  {
    id: "txn_flight",
    name: "Delta Air Lines",
    merchantName: "Delta",
    amount: 488,
    date: "2026-03-11",
    primaryCategory: "TRAVEL",
    detailedCategory: "TRAVEL_FLIGHTS",
    confidence: "HIGH",
    pending: false,
  },
  {
    id: "txn_netflix",
    name: "Netflix",
    merchantName: "Netflix",
    amount: 19,
    date: "2026-03-19",
    primaryCategory: "ENTERTAINMENT",
    detailedCategory: "ENTERTAINMENT_TV_AND_MOVIES",
    confidence: "VERY_HIGH",
    pending: false,
  },
  {
    id: "txn_gym",
    name: "Equinox",
    merchantName: "Equinox",
    amount: 205,
    date: "2026-03-18",
    primaryCategory: "PERSONAL_CARE",
    detailedCategory: "PERSONAL_CARE_GYMS_AND_FITNESS_CENTERS",
    confidence: "HIGH",
    pending: false,
  },
  {
    id: "txn_uber",
    name: "Uber",
    merchantName: "Uber",
    amount: 44,
    date: "2026-03-20",
    primaryCategory: "TRANSPORTATION",
    detailedCategory: "TRANSPORTATION_TAXIS_AND_RIDE_SHARES",
    confidence: "HIGH",
    pending: true,
  },
  {
    id: "txn_payroll_feb",
    name: "Helios Labs Payroll",
    merchantName: "Helios Labs",
    amount: -6400,
    date: "2026-02-15",
    primaryCategory: "INCOME",
    detailedCategory: "INCOME_WAGES",
    confidence: "VERY_HIGH",
    pending: false,
  },
  {
    id: "txn_trip_hotel",
    name: "Ace Hotel",
    merchantName: "Ace Hotel",
    amount: 620,
    date: "2026-02-12",
    primaryCategory: "TRAVEL",
    detailedCategory: "TRAVEL_LODGING",
    confidence: "HIGH",
    pending: false,
  },
  {
    id: "txn_utilities",
    name: "Pacific Gas & Electric",
    merchantName: "PG&E",
    amount: 142,
    date: "2026-02-08",
    primaryCategory: "RENT_AND_UTILITIES",
    detailedCategory: "RENT_AND_UTILITIES_GAS_AND_ELECTRICITY",
    confidence: "HIGH",
    pending: false,
  },
  {
    id: "txn_dining",
    name: "Nopa",
    merchantName: "Nopa",
    amount: 134,
    date: "2026-01-29",
    primaryCategory: "FOOD_AND_DRINK",
    detailedCategory: "FOOD_AND_DRINK_RESTAURANT",
    confidence: "HIGH",
    pending: false,
  },
  {
    id: "txn_payroll_jan",
    name: "Helios Labs Payroll",
    merchantName: "Helios Labs",
    amount: -6200,
    date: "2026-01-15",
    primaryCategory: "INCOME",
    detailedCategory: "INCOME_WAGES",
    confidence: "VERY_HIGH",
    pending: false,
  },
  {
    id: "txn_invest",
    name: "Brokerage Transfer",
    merchantName: "Apex Invest",
    amount: 900,
    date: "2026-01-12",
    primaryCategory: "TRANSFER_OUT",
    detailedCategory: "TRANSFER_OUT_INVESTMENT_AND_RETIREMENT_FUNDS",
    confidence: "MEDIUM",
    pending: false,
  },
];

